### ISSUE TITLE
Ajouter une colonne "Notifications" dans la page des utilisateurs [redmine:27287]

### ISSUE THREAD

**Issue by yblatti** [asit-asso/extract#197]
**Original author :** Rémi Bovard

Finalisation de https://github.com/asit-asso/extract/issues/170#issuecomment-897503690

Afficher si les notifications sont actives pour un utilisateur dans la liste

*Maquette*

![notif](https://user-images.githubusercontent.com/2951929/129202921-0c4c80cc-db5e-41b9-aef4-f1f902d0430c.png)

*Critères d’acceptation*

|ID|Critère|
|-------|-----|
|*27287-1*|un label affiche "Actives" ou "Inactives" selon la préférence de notifications du compte|

**Budget :** 546

**Comment by rbovard** [comment]
Est-ce que l'on ne pourrait pas taguer ce genre de modifications en "Easy fix" (ou quelque chose de similaire), pour encourager la communauté à faire ce genre de modifications que de passer par un prestataire ?

**Comment by yblatti** [comment]
En release 2.0 : https://github.com/asit-asso/extract/releases/tag/v2.0.0
