### ISSUE TITLE
Email de rappel si demande en attente de validation depuis > x jours [redmine:28406]

### ISSUE THREAD

**Issue by yblatti** [asit-asso/extract#202]
**Original author :** D. Gnerre :

### Objectif 

Lorsqu’une demande est faite, un email est envoyé avec un lien pour la validation. Ce qui arrive régulièrement dans quelques communes ici, c’est qu’ils oublient de traiter l’une ou l’autre demande. Il faudrait pouvoir configurer un rappel, qui renvoie automatiquement un email après X jours si la demande n’est pas traitée.

### Configuration

Dans la configuration générale d'Extract (`/parameters` bloc Orchestration), on peut configurer le nombre de jours entre les relance d'email à l'opérateur (champ entier). Saisir 0 (zéro) permet de désactiver la fonctionnalité.
Label : `Intervalle entre les rappels de validation (0 pour désactiver)`
La valeur par défaut à l'installation est 0.

### Comportement

Extract renvoie l'email de validation aux opérateurs d'un traitement lorsqu'une demande est en attente de validation depuis plus de <valeur-configurée> joursou que le dernier rappel date plus de <valeur-configurée> jours.

### Critères d'acceptation

|id|critère|
|---|---|
|202-1|Seul l'administrateur peut configurer le délais de rappel|
|202-2|Un email de validation est renvoyé après <valeur-configurée> jours si la demande est en attente de validation |
|202-3|Un email de validation est renvoyé si le dernier rappel date plus de <valeur-configurée> jours |

**Comment by rbovard** [comment]
1. Ne faudrait-il pas plutôt parler de jours que d'heures ?
2. Il doit manquer la fin du critère 202-2
    3. ... en état **validation en attente** (ou quelque chose de similaire, je n'ai pas le statut exact en tête)

**Comment by guillaumestark** [comment]
Oui merci pour les remarques, c'est corrigé!
