### ISSUE TITLE
Améliorer la visibilité de la remarque du client

### ISSUE THREAD

**Issue by gnerred** [asit-asso/extract#234]
## Objectifs
Donner la possibilité aux administrateurs de choisir des propriétés à mettre en avant lors de la validation opérateur et améliorer la visibilité de celles-ci.

## Configuration
Dans les paramètres généraux `/parameters`, renommer le bloc "Messages de validation" en "Validation"

Dans ce bloc, ajouter un nouveau champ :

    Label : Propriétés à mettre en avant lors de la validation

    Type de champ : Tags Input

    Placeholder : Veuillez saisir une propriété et appuyer sur Enter

![Settings_1](https://user-images.githubusercontent.com/17881679/228143919-72965f93-3612-4372-a418-b494f94a420a.png)
![Settings_2](https://user-images.githubusercontent.com/17881679/228143927-31401589-a3dc-46c0-b1d3-f36c4f6d2a81.png)

## Affichage lors de la validation
Les propriétés définies dans les paramètres sont mises en avant lors de la validation opérateur.

![validation](https://user-images.githubusercontent.com/17881679/228144004-b0b8ae49-4cbd-4db7-bc47-bf399b9a55bd.png)

## Critères d'acceptation
|Identifiant|Description|
| --- | --- |
| 255-1 | Seuls les administateurs peuvent éditer le champ texte "Propriétés à mettre en avant" |
| 255-2 | Le champ "Propriétés à mettre en avant" est vide par défaut |
| 255-4 | Les propriétés qui n'ont pas de valeurs ne doivent pas être affichées dans le bloc orange pendant la validation |
| 255-5 | Le bloc orange durant la validation doit uniquement s'afficher si au moins une propriété mise en avant contient une valeur |

____

Message original : La remarque client n'est pas très visible dans Extract pour la personne effectuant la validation de la commande. Dans le but d'éviter de rater ces remarques, le SIGE souhaite qu'elle puisse être mieux mise en évidence, comme c'est le cas dans Viageo par exemple. L'image attachée montre la proposition. 
![image](https://user-images.githubusercontent.com/1989467/155940327-9f88cb0d-0ea8-4918-aea7-0ff221c403f2.png)

**Comment by gnerred** [comment]
Salut Guillaume. Oui on peut changer le style, par contre celui proposé n'a pas assez de contraste avec le fond, as-tu une autre proposition ?

**Comment by gnerred** [comment]
Oui ça me parait bien merci ;-)

**Comment by rbovard** [comment]
Les deux maquettes ne correspondent pas, qu'est-ce qui va être implémenté ?

![image](https://user-images.githubusercontent.com/4549666/230405893-9de3c588-97e8-43ab-9051-bf42c7798fe1.png)

![image](https://user-images.githubusercontent.com/4549666/230405962-552b572d-8e63-4767-ad12-ac244b0d174e.png)

**Comment by guillaumestark** [comment]
@rbovard La version implémentée sera celle décrite dans le premier message (avec REMARK, PROJECT, FORMAT)
