### ISSUE TITLE
Administration : Afficher le dossier des fichiers temporaires d'une commande

### ISSUE THREAD

**Issue by ponceta** [asit-asso/extract#237]
## Objectifs
Afficher l'emplacement des fichiers temporaires d'une commande.

## Configuration
Dans les paramètres, dans le bloc Orchestration :
- Renommer `Chemin de stockage` en `Emplacement des fichiers temporaires`
- Ajouter un nouveau toggle
   - Label :  Afficher l'emplacement des fichiers temporaires aux opérateurs
   - Valeur par défaut: Non

![settings](https://user-images.githubusercontent.com/17881679/227947189-51f71885-cc44-4e9a-afbf-65238c89b756.png)

## Affichage lors de la validation
Lors d'un traitement, dans le bloc Réponse au client 
 - Ajouter l'emplacement des fichiers temporaires

![validation](https://user-images.githubusercontent.com/17881679/227947197-0b61e4b9-3d8e-458a-839d-6b7b87ba938d.PNG)

## Critères d'acceptation
|Identifiant|Description|
| --- | --- |
| 237-1 | Seul un administrateur peut paramètrer ce nouveau toggle
| 237-2 | Le toggle doit avoir la valeur "Non" par défaut
| 237-3 | les administrateurs voient toujours l'emplacement des fichiers
| 237-4 | Les opérateurs voient uniquement l'emplacement des fichiers temporaires si le toggle est activé dans les réglages

Message original : Afin de plus facilement identifier les fichiers d'une commande.

![image](https://user-images.githubusercontent.com/8614223/163134993-e456ca14-5179-4ca8-a88a-34123c18bf7c.png)

Dans l'onglet administration d'une commande :

![image](https://user-images.githubusercontent.com/2951929/216051515-1c9cce5c-4a37-486e-8e71-005333c946a7.png)

**Comment by yblatti** [comment]
Merci pour ce retour.
Attention, ce n'est pas le guid de la commande (transmis par le web service), il faudrait plutôt indiquer "Dossier des fichiers temporaires".
