### ISSUE TITLE
Ajouter un filtre dans la page des traitements

### ISSUE THREAD

**Issue by rogermaurer** [asit-asso/extract#256]
Pour faciliter la recherche d'un traitement dans une liste sur plusieurs pages, nous souhaitons ajouter un champ permettant de filtrer les traitements par leur noms.

**Comment by rbovard** [comment]
Ca me semble déjà réglé car il est déjà possible de filtrer par traitement *(en jaune)*, et au besoin on peut combiner un mot-clé *(en vert)*

![image](https://user-images.githubusercontent.com/4549666/215741100-40766ab8-2d94-400b-b87e-66036ccf6413.png)

**Comment by rogermaurer** [comment]
Effectivement, c'est maintenant possible. Merci pour l'information.
