### ISSUE TITLE
Boite au lettre partagée – Envoi des messages d’avertissement pour traiter une demande

### ISSUE THREAD

**Issue by rogermaurer** [asit-asso/extract#267]
En plus de l'envoi des messages pour avertir les opérateurs de traiter une demande, il y a des services qui souhaitent recevoir ces e-mails également dans leurs boites aux lettres partagée.
Notre politique de sécurité limite l’accès à Extract via des comptes d’utilisateurs personnels. De ce fait, nous souhaitons qu’on puisse rajouter les e-mails pour les boites aux lettres partagées aux groupes d’utilisateurs permettant ainsi l’envoi des message d’avertissement sans création d’un compte d’utilisateurs. 
La connexion à Extract pour traiter la demande continuera à se faire via des comptes d’utilisateurs personnels.

**Comment by rogermaurer** [comment]
Bonjour Yves,

Merci pour les options indiquées.
L'option 2 ne convient pas vraiment car le mot de passe des comptes utilisateurs pourrait être réinitialisé.
Nous allons tester l'option 1 avec les services demandant l'envoi des messages à leurs boites aux lettres partagées.

Je te tiens au courant du résultat.
A+, Roger

**Comment by yblatti** [comment]
@rogermaurer, des nouvelles sur ce sujet ? La solution 1 convient-elle ?

**Comment by rogermaurer** [comment]
La solution 1 est utilisée depuis quelques semaines par l'un des partenaires CartoJuraLéman et elle semble convenir.
Encore merci pour le conseil.
