### ISSUE TITLE
Supprimer le bouton pour afficher la liste des connecteurs dans l’interface opérateur

### ISSUE THREAD

**Issue by rogermaurer** [asit-asso/extract#268]
Message original de @rogermaurer : 
L'opérateur peut voir la liste de tous les connecteurs actifs via un bouton en haut à droite de l’interface, même s'il n'est pas opérateur attitré aux traitements liés à ces connecteurs.
En plus, l'opérateur ne peut qu'afficher la liste des connecteurs via ce bouton sans déclencher une fonction.
C'est pourquoi, nous souhaitons cacher ce bouton car il est inutile dans l'interface de l'opérateur.

## Situation actuelle
![bouton-connecteur](https://user-images.githubusercontent.com/17881679/226271497-5b8e980d-d2dc-4639-bd97-9b7ef69ac13e.png)

Le bouton qui liste les connecteurs fonctionnels présente peu d'intérêt pour les opérateurs, car celui-ci leur permet uniquement de lister les connecteurs, sans pouvoir y effectuer une quelconque action.

## Résolution
Pour éviter d'encombrer l'interface des opérateurs, il faut leur supprimer le bouton connecteurs "succès".

## Critères d'acceptation
|Identifiant|Description|
| --- | --- |
| 268-1 | Dans l'interface opérateur, supprimer le bouton qui liste les connecteurs fonctionnels. |
| 268-2 | Le bouton qui liste les connecteurs avec erreurs doit rester visible pour les rôles administrateurs et opérateurs. |
| 268-3 | Le bouton qui liste les connecteurs avec succès doit rester visible pour les rôles administrateurs. |

**Comment by yblatti** [comment]
Bonjour Roger,

Effectivement un opérateur ne peut pas effectuer d'opérations sur un connecteur. ceci est limité aux administrateurs.

Par contre, le bouton permet à l’opérateur de voir les informations sur l'état des connecteurs : 
- **En cas d'erreur (rouge)**, connaitre la raison : 
![image](https://user-images.githubusercontent.com/2951929/204838314-2124ff16-1ddd-40d0-a215-e775e5108669.png)
- **Quand tout va bien (vert)**, connaitre le dernier import réussi
![image](https://user-images.githubusercontent.com/2951929/204838500-1a692b62-c52a-4e32-93ff-71071bea6790.png)

**Ceci ne présente aucun intérêt pour vos opérateurs ?**
Si ce n'est pas le cas, nous pourrions voter ce retrait à la prochaine rencontre utilisateur.

NB : à ma connaissance on ne pourra pas limiter les connecteurs à ceux liés au traitements d'un opérateur à cause du système de règles de correspondance qui dépendent des données de chaque requête (données dynamiques).

**Comment by rogermaurer** [comment]
Merci Yves pour ton commentaire.

Dans le cas de CartoJuraLéman (CJL), l'opérateur risque de voir une quarantaine de connecteurs qui ne le concerne pas.
Il risque donc plutôt être perturbé si on affiche les connecteurs dans son interface. 
Pour consulter l'état des traitements, je trouve personnellement qu'il est plus adéquat d'ouvrir le traitement directement au lieu de consulter des infobulles sur les connecteurs où les informations sont que partielles.

Je propose donc de voter ce retrait à la prochaine rencontre utilisateur.
