### ISSUE TITLE
FME Desktop : certaines extractions se bloquent

### ISSUE THREAD

**Issue by yblatti** [asit-asso/extract#269]
_Remonté par la Ville de Vevey (D. Gnerre), sur Windows Server_

Lors de l’exécution de certaines extractions avec FME Desktop, avec un gros jeu de donnée, l'extraction de bloque : 
- il n'y a plus d'entrées dans le log FME
- il ne se passe rien dans Extract
Si on redémarre Extract, le processus FME reprend immédiatement là ou il a été bloqué.

Ceci semble indiquer que le couplage Extract <-> FME bloque l’exécution, et que lorsque l'on redémarre Extract, le processus est détaché  et continue.

**Comment by yblatti** [comment]
Ma piste est la suivante : 

Sur les gros jeux de données, l'output FME est plus important (plus de lignes de sorties).
Extract ne lit ni ne redirige les sorties du processus FME lancé. Nous atteignons certainement une limite de buffer (OS ? java ?).

Il faudrait peut être tester une des pistes suivantes : 
- Lire les buffers pour les vider (output et error) avec `Process.getInputStream()` et `Process.getErrorStream()`
- Executer CMD au lieu de FME directement et rediriger la sortie shell, par exemple `cmd /c [chemin_vers_fme.exe et les parametres] 2> nul`
- Utiliser `ProcessBuilder.start()` au lieu de `Runtime.exec()` avec `redirectOutput `et `redirectError`

**Comment by yblatti** [comment]
La documentation va dans ce sens : https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Process.html

> By default, the created process does not have its own terminal or console. All its standard I/O (i.e. stdin, stdout, stderr) operations will be redirected to the parent process, where they can be accessed via the streams obtained using the methods [getOutputStream()](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Process.html#getOutputStream()), [getInputStream()](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Process.html#getInputStream()), and [getErrorStream()](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Process.html#getErrorStream()). The I/O streams of characters and lines can be written and read using the methods [outputWriter()](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Process.html#outputWriter()), [outputWriter(Charset)](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Process.html#outputWriter(java.nio.charset.Charset))}, [inputReader()](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Process.html#inputReader()), [inputReader(Charset)](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Process.html#inputReader(java.nio.charset.Charset)), [errorReader()](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Process.html#errorReader()), and [errorReader(Charset)](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Process.html#errorReader(java.nio.charset.Charset)). The parent process uses these streams to feed input to and get output from the process. **Because some native platforms only provide limited buffer size for standard input and output streams, failure to promptly write the input stream or read the output stream of the process may cause the process to block, or even deadlock.**

**Comment by yblatti** [comment]
J'ai compilé un petit logger pour chercher la limite (pour remplacer FME.exe) : 

```c#
StreamWriter writer = new StreamWriter("superlogger.log");

const int MAX_LINES = 10000;

Int64 lineNumber = 1;

while (lineNumber <= MAX_LINES)
{
    Console.Write("X");
    writer.Write("X");
    writer.Flush();
    lineNumber++;
}
```

Cela permet de confirmer le comportement :
- Le lock se passe toujours à 4120 caractères, processus arrêté.
- Si on relance Extract, le processus est libéré et termine correctement.
- Si on execute avec moins de caractères en sortie (ex. 1000), tout se passe bien.

**Comment by maltaesousa** [comment]
Merci beaucoup @yblatti d'avoir trouvé la cause! Bien joué pour la petite démo simple et efficace :)
Est-ce que tu sais si ce problème est compris dans la garantie d'Extract et si on peut avoir un correctif assez rapidement? Chez nous cela signifie que toutes les commandes LiDAR 2022 (gros dataset) doivent être extraites à la main.

**Comment by yblatti** [comment]
Salut @maltaesousa ,

Git blame nous indique que les IO n'ont jamais été redirigés, et donc que c'est un bug présent depuis la v1.0.
Nous avons déjà commandé la correction qui devrait être réalisée début janvier, et sera prise en charge par le budget _bug_ de l'ASIT.

Nous espérons donc livrer une v2.0.2 très rapidement en 2023.

**Comment by maltaesousa** [comment]
Super, c'est parfait merci infiniment!

**Comment by yblatti** [comment]
Corrigé en [v2.0.2](https://github.com/asit-asso/extract/releases/tag/v2.0.2) merci @arxit-ygr
