### ISSUE TITLE
Masquer le mot de passe dans le traitement Extraction FME Server

### ISSUE THREAD

**Issue by j-briant** [asit-asso/extract#286]
Situation actuelle: le mot de passe est visible dans l'interface du traitement

![image](https://user-images.githubusercontent.com/74244150/235697550-d12ef73b-ff72-4e4d-8dd2-cc4132097d2d.png)

Situation voulue: le mot de passe est au moins masqué, voir n'est plus affiché une fois que le traitement est enregistré.

![image](https://user-images.githubusercontent.com/74244150/235698867-f9d9c8b0-9358-4916-95bc-ce5986c3ea34.png)

**Comment by guillaumestark** [comment]
Merci pour l'information, cette correction fera partie du prochain lot d'Extract.

J'ajoute quelques précisions pour l'implémentation : 

Après avoir renseigné le mot de passe d'un plugin Extraction FME / Extraction FME Server et sauvegarder le traitement : 
- Le mot de passe ne doit pas être remonté dans le frontend
- Le champ mot de passe doit être rempli de ********
- Il doit être possible de saisir un nouveau mot de passe et de le mettre à jour lors de l'enregistrement du traitement
