### ISSUE TITLE
Supporter OAuth 2.0 pour l'envoi SMTP

### ISSUE THREAD

**Issue by yblatti** [asit-asso/extract#290]
Afin de pouvoir utiliser des serveur SMTP externes, par exemple ceux de Microsoft (Office 365, Microsoft 365, exchange online...) il faudrait permettre de s'authentifier par OAuth 2.0.

_Demandeur : SEIC Gland_

**Comment by guillaumestark** [comment]
Besoin non partagé par le reste du GU / SEIC utilisera un relais SMTP
