### ISSUE TITLE
Comment déclencher un traitement ?

### ISSUE THREAD

**Issue by acerioni** [asit-asso/extract#291]
Bonjour,

Je souhaiterais effectuer des tests fonctionnels d'Extract afin d'évaluer l'opportunité de son intégration au sein de la plateforme SIG de l'Etat de Genève. 

J'ai bien réussi à démarrer une instance locale d'Extract, à accéder à son interface d'administration par le compte `admin` et à configurer quelques traitements. Une fois un traitement configuré, comment peut-on le déclencher ?

Merci d'avance pour votre aide,
Alessandro Cerioni - Etat de Genève

**Comment by yblatti** [comment]
Bonjour,

Le principe de fonctionnement est le suivant : 

- Un connecteur est chargé de créer des requêtes dans le système, en les important d'un système externe.
- La requête comporte, quelques identifiants (produit, client, organisme, evt tiers, etc), un périmètre géographique, et un dictionnaire de propriétés (p.ex. Format, projection, type de découpe, remarque...)
- Une fois la requête créée elle passe dans des règles de correspondances du connecteur, qui font correspondre cette requête à un traitement. La matching peut se faire du des identifiants, de propriété, la géométrie etc.
-

**Comment by acerioni** [comment]
Merci @yblatti pour votre retour, c'est beaucoup plus clair 🙂

Effectivement, en suivant [cette doc](https://viageo.ch/api/legacyOrder/doc), j'ai réussi à implémenter une émulation d'un service distant et alors tester la remontée de commandes dans Extract.

Alessandro
