### ISSUE TITLE
Périmètre de requête vide lors d'une commande par grille kilométrique

### ISSUE THREAD

**Issue by j-briant** [asit-asso/extract#296]
J'ignore si le soucis est plus du côté viageo ou Extract.

**Situation actuelle**: Si une donnée du catalogue viageo est commandée avec un périmètre de commande de type _grille kilométrique_, la géométrie n'est pas transmise à Extract et provoque une erreur:

Début | Fin | Tâche | Statut / Message | Utilisateur
-- | -- | -- | -- | --
2024-04-04 13:46:51 | 2024-04-04 13:46:51 | Import | Erreur / Cet élément n'a pas de périmètre géographique, il ne pourra pas être traité. | Système

![image](https://github.com/asit-asso/extract/assets/74244150/05d8f584-e3ec-439e-b694-ac4a244cd889)

**Situation voulue**: Les grilles sélectionnées sont transmises à Extract et ne provoquent pas d'erreur, permettant l'extraction.

**Contournement**: Désactiver la commande par grille, surtout dans le cas de données téléchargeables directement. Convient parfaitement dans le cas de données ouvertes mais pourrait poser problème si la commande par grille kilométrique est nécessaire.

**Informations complémentaires**:  Version 2.0.2-RELEASE

**Comment by yblatti** [comment]
C'est un problème connu : https://github.com/asit-asso/extract/issues/133

Aujourd'hui, si l'on commande avec un périmètre prédéfini (commune, grille kilométrique, etc) on reçoit un code au lieu d'une géométrie.

Il faudrait une correction côté Extract + côté viageo. **Ou** uniquement côté viageo et permettre de configurer son webservice pour choisir si l'on désire recevoir des codes (comme aujourd'hui) ou des géométries agrégées en un multi-polygone.

Est-ce une évolution qui vous intéresse pour le futur ?

**Comment by j-briant** [comment]
Oh je n'avais pas fait le lien entre les tickets.
Je ne vois pas de situation dans laquelle on préfèrera commander par grille plutôt que par polygone. Par commune pourrait être intéressant, mais à ce stade j'ai un doute sur le fait que commande soit la bonne procédure, j'aurais tendance à privilégier un téléchargement direct.

En bref:

* intéressant --> oui 
* nécessaire --> non

**Comment by yblatti** [comment]
Merci pour ton retour !

Je propose donc qu'on close ce ticket en faveur de l'original.
