### ISSUE TITLE
2.1-BETA.1 : Ajouter dans la doc que les mots de passes des connecteurs sont à réinitialiser en cas de MAJ

### ISSUE THREAD

**Issue by maltaesousa** [asit-asso/extract#297]
A la page 5 du manuel d'installation, ajouter un point 11 du style:
- Les mots de passes des connecteurs doivent être entrées une fois Extract redémarré

![image](https://github.com/asit-asso/extract/assets/3328875/5910b0d8-f06d-400f-9c6d-2eb89f558467)

Après avoir re-rentré les mots de passe, les connecteurs fonctionnent à nouveau

**Comment by yblatti** [comment]
Je n'ai pas rencontré ce problème, était-ce peut-être lié à https://github.com/asit-asso/extract/issues/295 ?
Mes mots de passe sont toujours valides après la mise à jour.

J'ai néanmoins remonté le bug à arx iT : réf interne FS#23355

**Comment by maltaesousa** [comment]
Je viens de suivre la procédure et j'ai dû remettre les mots de passe des connecteurs. Pour le mot de passe de l'utilisateur, pas besoin.
