### ISSUE TITLE
Extract V2.1 - Heures de fonctionnement 

### ISSUE THREAD

**Issue by efac-fb** [asit-asso/extract#317]
L'ajout et la modification d'une plage d'heures de fonctionnement d'Extract est impossible dans la configuration de l'application.
Il semble qu'il y ait un  soucis avec le format de date/heure.
![erreur_extract_plage_fonctionnement](https://github.com/user-attachments/assets/52fb511c-2c6c-46da-9c49-2a7ce5975db9)

Reproduction de l'erreur:

1. Page "Paramètres"
2. Ajouter ou modifier un plage de fonctionnement
3. Enregistrer

**Comment by yblatti** [comment]
Remonté pour correction (en principe sous garantie) : ref interne FS#23515

**Comment by yblatti** [comment]
Bloquant car si c'est une option active, il est impossible de modifier la config Extract en entier.

**Comment by yblatti** [comment]
Fixé en v2.1.1, merci @arxit-ygr
